version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5.0.6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
  api:
    container_name: api-container
    image: node:17-alpine
    restart: always
    ports:
      - '8000:8000'
      - '9000:9000'
    working_dir: /usr/src/api
    command: sh -c "yarn install --prod && yarn debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/api
    volumes:
      - ./dist/:/usr/src/api/dist/
      - ./package.json:/usr/src/api/package.json
